permalink:      /:title.html
paginate:       10
#markdown:       redcarpet
highlighter:    pygments
excerpt:        ""

# 作者信息
author:
    name:   guofeng
    email:  guofeng@eatingfirst.com
    link:   http://blog.eatingfirst.com
    github: https://github.com/ticty
    music:  http://www.xiami.com/u/36466652

# 站点信息
title:          Ticty's Blog
description:    Personal Blog
url:            http://blog.eatingfirst.com
rss_url:        /pages/atom.xml

# gavatar头像及Favicon
gavatar:    /public/img/gavatar.ico
favicon:    /public/img/favicon.png

# google analytics 设置
ga:
    id:     UA-59482376-1
    url:    http://blog.eatingfirst.com

# disqus 设置
disqus:
    shortname:  tictyblog

# 中文本地化
locals:
    tags:       标签
    about:      关于
    newest:     最新文章
    archive:    归档

